M48
; DRILL file {KiCad 7.0.0} date vr 24 feb 2023 19:47:00 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-24T19:47:00+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1693
%
G90
G05
T1
X1.7717Y-1.0335
T2
X1.2598Y-1.1024
X1.2598Y-3.2677
X3.4252Y-1.1024
X3.4252Y-3.2677
T0
M30
